package com.knoxhack.echothemecore.api;

public enum EchoThemeTextureKey {
    BACKGROUND,
    PANEL,
    PANEL_ALT,
    BUTTON,
    BUTTON_HOVER,
    TAB,
    TAB_ACTIVE,
    MISSION_CARD,
    MISSION_CARD_SELECTED,
    STATUS_CHIP,
    PROGRESS_BAR,
    SCROLLBAR,
    ICON_PACK,
    HOLOGRAM_OVERLAY,
    ENERGY_OVERLAY,
    EDGE_GLOW,
    PARTICLE_GLINTS,
    LOCKED_OVERLAY,
    VANILLA_BACKGROUND,
    VANILLA_PANEL,
    VANILLA_BUTTON,
    VANILLA_HOTBAR,
    VANILLA_TOOLTIP,
    VANILLA_TOAST,
    VANILLA_BOSS_BAR
}
