package com.knoxhack.echostationfall.registry;

import net.neoforged.bus.api.IEventBus;

public final class ModWorldgen {
    private ModWorldgen() {
    }

    public static void register(IEventBus eventBus) {
        // Stationfall is a single saved station route generated by StationfallStationGenerator
        // when the player boards. It intentionally does not register biome or chunk features.
    }
}
